### ISSUE TITLE
From mermaid to decisionSupport

### ISSUE THREAD

**Issue by CWWhitney** [noviriasyifaunnafsi/thesis-project-transition-from-rice-to-vegetables#1]
We have a nice graph 
![IMG_4231](https://github.com/nafsi20/thesis-project-transition-from-rice-to-vegetables/assets/19190662/5c2e6505-c6f4-45a3-b65b-702e54038566)

@nafsi20 you built it in mermaid. 
[thesis-project-transition-from-rice-to-vegetables](https://github.com/nafsi20/thesis-project-transition-from-rice-to-vegetables/tree/main)/conceptual model.R

Now can we build it in decisionSupport? 

Look for a simple example here: 

https://cran.r-project.org/web/packages/decisionSupport/vignettes/example_decision_function.html

**Comment by noviriasyifaunnafsi** [comment]
let me try it, thanks!

**Comment by noviriasyifaunnafsi** [comment]
@CWWhitney I just created the script for decisionSupport here:
https://github.com/nafsi20/thesis-project-transition-from-rice-to-vegetables/blob/main/decision%20support.R

Since we haven't decided the intervention yet (right?), I just typed the intervention as 'notknownyet'.

Hope it works~

**Comment by CWWhitney** [comment]
Excellent - @noviriasyifaunnafsi #[c2d1e4a](https://github.com/noviriasyifaunnafsi/thesis-project-transition-from-rice-to-vegetables/commit/c2d1e4a160fe0ae4fcc73de7bad104f6aa6b7f2e)

https://github.com/nafsi20/thesis-project-transition-from-rice-to-vegetables/blob/main/decision%20support.R

That is a good start.
