### ISSUE TITLE
Issue with the .csv

### ISSUE THREAD

**Issue by CWWhitney** [noviriasyifaunnafsi/thesis-project-transition-from-rice-to-vegetables#2]
Minor: 
@noviriasyifaunnafsi 
Please remove the strange ~~ symbols in the name of the csv

[input_rice_to_vegs~~.csv](https://github.com/noviriasyifaunnafsi/thesis-project-transition-from-rice-to-vegetables/blob/main/input_rice_to_vegs~~.csv)

**Comment by noviriasyifaunnafsi** [comment]
I'm sorry, my bad. I have renamed it.
